### ISSUE TITLE
NameError: name 'vs' is not defined

### ISSUE THREAD

**Issue by Vict0rSch** [NickShahML/tensorflow_with_latest_papers#15]
Trying to use your MultiRNNCell with residual connections however at graph creation time i get a " NameError: name 'vs' is not defined " from line 54 of rnn_wrappers_modern.py... Is there something I'm doing wrong? 

I create the cells just like in your example.

Thanks for your help!

**Comment by NickShahML** [comment]
Simply replace "vs" with "tf" -- it wasn't imported properly.
