### ISSUE TITLE
Additional input features

### ISSUE THREAD

**Issue by renzhe0009** [NickShahML/tensorflow_with_latest_papers#17]
Hi,
Great work!
But did you have a plan to implement additional input features?
Like the paper:
Linguistic Input Features Improve Neural Machine [Translation](https://arxiv.org/pdf/1606.02892.pdf) (Senrich et al. 2016)
and implement in torch:
https://github.com/harvardnlp/seq2seq-attn/commit/cb18ac30bb3a586924d2fcfacc5a67a20ede81c8

Thank you very much for sharing such great code！

**Comment by NickShahML** [comment]
Hey @renzhe0009 , thanks for asking. Right now I try to write code when I can in my free time. According to the paper though, you should be able to enter your input as a concat of whatever additional input features you want and it should still work :)

**Comment by renzhe0009** [comment]
Hi，
Thanks for reply.

In that paper,chapter 2.1,the equation(2)
|| is the vector concatenation,
Is that means we should evaluate the feature's embedding and word's embedding by separately, and input them as a concat in Encoder , just like what you said.
By tensorflow,just use EmbeddingWrapper function and array_ops.concat
Do you agree?

Thanks again for your patience.

**Comment by NickShahML** [comment]
Yes simply concat on axis 1 and insert it as the input into the encoder

**Comment by renzhe0009** [comment]
Thanks,
And we should separate the feature and the word from data, 
build the vocab for feature and word separately , 
make the encoder_inputs_feature and encoder_inputs_nofeature ,
then build the seq2seq model  by using EmbeddingWrapper function and array_ops.concat function
......

**Comment by ashern** [comment]
FWIW - I'm pretty sure that the EmbeddingWrapper is deprecated as of TF
1.2. You should put together that functionality without the wrapper.

**Comment by renzhe0009** [comment]
@ashern 
Errrrrr,
OKay, remain tf-0.12
